- team_name: Arizona Diamondbacks
  team_id: '109'
  league: NL
  abbr: ARI
- team_name: Atlanta Braves
  team_id: '144'
  league: NL
  abbr: ATL
- team_name: Baltimore Orioles
  team_id: '110'
  league: AL
  abbr: BAL
- team_name: Boston Red Sox
  team_id: '111'
  league: AL
  abbr: BOS
- team_name: Chicago Cubs
  team_id: '112'
  league: NL
  abbr: CHC
- team_name: Chicago White Sox
  team_id: '145'
  league: AL
  abbr: CWS
- team_name: Cincinnati Reds
  team_id: '113'
  league: NL
  abbr: CIN
- team_name: Cleveland Indians
  team_id: '114'
  league: AL
  abbr: CLE
- team_name: Colorado Rockies
  team_id: '115'
  league: NL
  abbr: COL
- team_name: Detroit Tigers
  team_id: '116'
  league: AL
  abbr: DET
- team_name: Houston Astros
  team_id: '117'
  league: AL
  abbr: HOU
- team_name: Kansas City Royals
  team_id: '118'
  league: AL
  abbr: KC
- team_name: Los Angeles Angels
  team_id: '108'
  league: AL
  abbr: LAA
- team_name: Los Angeles Dodgers
  team_id: '119'
  league: NL
  abbr: LAD
- team_name: Miami Marlins
  team_id: '146'
  league: NL
  abbr: MIA
- team_name: Milwaukee Brewers
  team_id: '158'
  league: NL
  abbr: MIL
- team_name: Minnesota Twins
  team_id: '142'
  league: AL
  abbr: MIN
- team_name: New York Mets
  team_id: '121'
  league: NL
  abbr: NYM
- team_name: New York Yankees
  team_id: '147'
  league: AL
  abbr: NYY
- team_name: Oakland Athletics
  team_id: '133'
  league: AL
  abbr: OAK
- team_name: Philadelphia Phillies
  team_id: '143'
  league: NL
  abbr: PHI
- team_name: Pittsburgh Pirates
  team_id: '134'
  league: NL
  abbr: PIT
- team_name: San Diego Padres
  team_id: '135'
  league: NL
  abbr: SD
- team_name: San Francisco Giants
  team_id: '137'
  league: NL
  abbr: SF
- team_name: Seattle Mariners
  team_id: '136'
  league: AL
  abbr: SEA
- team_name: St. Louis Cardinals
  team_id: '138'
  league: NL
  abbr: STL
- team_name: Tampa Bay Rays
  team_id: '139'
  league: AL
  abbr: TB
- team_name: Texas Rangers
  team_id: '140'
  league: AL
  abbr: TEX
- team_name: Toronto Blue Jays
  team_id: '141'
  league: AL
  abbr: TOR
- team_name: Washington Nationals
  team_id: '120'
  league: NL
  abbr: WSH