options(stringsAsFactors = FALSE)
library(urltools)
library(stringr)
library(stringi)
library(purrr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(R6)
library(shiny)
library(shinyjs)
library(zoo)

source('src/shiny_utils.R')
source('classes/data_fetcher.R')
source('classes/pitcher.R')
source('classes/hitter_class.R')
teams <- jsonlite::read_json('config/team_ref.json', 
                             simplifyVector = TRUE)
